name: pr-validation-wf
on: 
 pull_request:
   types:
     - opened
     - synchronize
 push:
    branches:
      - develop
jobs:
  pr-validation-job:
   runs-on: ubuntu-latest
   steps:
     - name: firststep
       run: echo "Welcome to the Github actions" 
     - name: secondstep
       run: echo "this is second step"
